app:
  defaultLanguage: en
  fileCache:
    # period for deletion of cache
    cleaningJobRate: PT24H # 24 hours period, ISO_8601
    path: /tmp/cache
    pdfPath: /tmp/pdfcache
    # delete files older than X hours
    expirationTerm: 23 # hours
server:
  port: 8080
  servlet:
    context-path: /RMBTStatisticServer_new
spring:
  http:
    multipart:
      enabled: false
  application:
    name: statistic-backend
  datasource:
    poolSize: 20
    minIdle: 1
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${STATISTIC_DB_HOST}:${STATISTIC_DB_PORT}/${STATISTIC_DB_NAME}
    username: ${STATISTIC_DB_USER}
    password: ${STATISTIC_DB_PASSWORD}

#    tomcat:
#      test-while-idle: true
#      test-on-borrow: true
#      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
  flyway:
    enabled: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
RMBT_SECRETKEY: RMBT_SECRETKEY

application-version:
  host: rtr-api-dev

redis:
  host: localhost
  port: 6379
---
spring:
  profiles: dev
  datasource:
    poolSize: 20
    minIdle: 1
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URI}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
#    tomcat:
#      test-while-idle: true
#      test-on-borrow: true
#      validation-query: SELECT 1

application-version:
  host: rtr-api-dev

redis:
  host: redis
  port: 6379
---
spring:
  profiles: test
  datasource:
    poolSize: 20
    minIdle: 1
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URI}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    tomcat:
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1

application-version:
  host: rtr-api-test

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
---
spring:
  profiles: prod
  datasource:
    poolSize: 20
    minIdle: 1
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${STATISTIC_DB_HOST}:${STATISTIC_DB_PORT}/${STATISTIC_DB_NAME}
    username: ${STATISTIC_DB_USER}
    password: ${STATISTIC_DB_PASSWORD}
    tomcat:
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1

application-version:
  host: ${HOST_ID}

redis:
  host: ${STATISTIC_REDIS_HOST}
  port: ${STATISTIC_REDIS_PORT}
logging:
  config: ${LOGGING_CONFIG_FILE_STATISTIC:classpath:logback.xml}