app:
  defaultLanguage: en
server:
  port: 8080
  servlet:
    context-path: /RMBTStatisticServer
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: statistic-backend
  datasource:
    poolSize: 20
    minIdle: 1
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5431/rtr
    username: rtr
    password: password

#    tomcat:
#      test-while-idle: true
#      test-on-borrow: true
#      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
  flyway:
    enabled: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
RMBT_SECRETKEY: RMBT_SECRETKEY

auth0:
  issuer: https://specure.eu.auth0.com/
  apiAudience: https://nettest.org

application-version:
  host: rtr-api-dev

logback:
  port: 5000
  host: http://127.0.0.1
---
spring:
  profiles: dev
  datasource:
    poolSize: 20
    minIdle: 1
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URI}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
#    tomcat:
#      test-while-idle: true
#      test-on-borrow: true
#      validation-query: SELECT 1


application-version:
  host: rtr-api-dev

logback:
  port: ${LOG_PORT}
  host: ${LOG_HOST}
---
spring:
  profiles: test
  datasource:
    poolSize: 20
    minIdle: 1
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URI}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    tomcat:
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1


application-version:
  host: rtr-api-test

logback:
  port: ${LOG_PORT}
  host: ${LOG_HOST}
---
spring:
  profiles: staging
  datasource:
    poolSize: 20
    minIdle: 1
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URI}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    tomcat:
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1


application-version:
  host: rtr-api-staging

logback:
  port: ${LOG_PORT}
  host: ${LOG_HOST}
